import AppLayout from '@/Layouts/AppLayout';
import FormField, { inputCls } from '@/Components/FormField';
import ProductPickerModal from '@/Components/ProductPickerModal';
import CustomerPickerModal from '@/Components/CustomerPickerModal';
import { Head, Link, useForm } from '@inertiajs/react';
import { useState, useEffect } from 'react';

const fmt = (n: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(n);

function buildVisitPlans(startDate: string, endDate: string, frequency: number): any[] {
    if (!startDate || !endDate || frequency < 1) return [];
    const start = new Date(startDate);
    const end   = new Date(endDate);
    if (isNaN(start.getTime()) || isNaN(end.getTime()) || start >= end) return [];

    const totalDays = (end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24);
    const intervalDays = totalDays / frequency;

    return Array.from({ length: frequency }, (_, i) => {
        const d = new Date(start.getTime() + intervalDays * i);
        return {
            visit_number: i + 1,
            planned_date: d.toISOString().slice(0, 10),
            notes: '',
        };
    });
}

export default function Form({ contract, customers, products, employees }: any) {
    const editing = !!contract;

    const { data, setData, post, put, processing, errors } = useForm<any>({
        customer_id:          contract?.customer_id          ?? '',
        contract_number:      contract?.contract_number      ?? '',
        start_date:           contract?.start_date           ?? '',
        end_date:             contract?.end_date             ?? '',
        contract_value:       contract?.contract_value       ?? '',
        service_area:         contract?.service_area         ?? '',
        visit_frequency:      contract?.visit_frequency      ?? 1,
        invoice_frequency:    contract?.invoice_frequency    ?? 1,
        status:               contract?.status               ?? 'draft',
        notes:                contract?.notes                ?? '',
        sales_type:           contract?.sales_type           ?? '',
        sales_employee_id:    contract?.sales_employee_id    ?? '',
        lead_employee_id:     contract?.lead_employee_id     ?? '',
        services: contract?.services?.map((s: any) => ({
            product_id:   s.product_id,
            quantity:     s.quantity,
            unit_price:   s.unit_price,
            total_price:  s.total_price,
            location:     s.location ?? '',
            sub_products: s.sub_products?.map((sp: any) => ({
                product_id: sp.product_id,
                quantity:   sp.quantity,
            })) ?? [],
        })) ?? [],
        visit_plans: contract?.visit_plans?.map((vp: any) => ({
            visit_number: vp.visit_number,
            planned_date: vp.planned_date ?? '',
            notes:        vp.notes ?? '',
        })) ?? [],
    });

    const [customerPickerOpen, setCustomerPickerOpen] = useState(false);
    const selectedCustomer = customers?.find((c: any) => String(c.id) === String(data.customer_id));

    const [pickerTarget, setPickerTarget] = useState<{ svcIdx: number; subIdx?: number } | null>(null);
    const [duplicateError, setDuplicateError] = useState('');

    const getProduct = (id: string) => products?.find((p: any) => p.id === id);

    // Auto-generate visit plans when frequency or dates change (only if plans not yet manually edited)
    const [plansAutoGenerated, setPlansAutoGenerated] = useState(!editing || !contract?.visit_plans?.length);

    const regeneratePlans = () => {
        const plans = buildVisitPlans(data.start_date, data.end_date, data.visit_frequency);
        setData('visit_plans', plans);
        setPlansAutoGenerated(true);
    };

    useEffect(() => {
        if (plansAutoGenerated) {
            const plans = buildVisitPlans(data.start_date, data.end_date, data.visit_frequency);
            setData('visit_plans', plans);
        }
    }, [data.start_date, data.end_date, data.visit_frequency]);

    const updateVisitPlan = (i: number, field: string, value: any) => {
        const plans = [...data.visit_plans];
        plans[i] = { ...plans[i], [field]: value };
        setData('visit_plans', plans);
        setPlansAutoGenerated(false);
    };

    // Services
    const updateService = (i: number, field: string, value: any) => {
        const services = [...data.services];
        services[i] = { ...services[i], [field]: value };
        if (field === 'quantity' || field === 'unit_price') {
            services[i].total_price = (services[i].quantity || 0) * (services[i].unit_price || 0);
        }
        if (field === 'product_id') {
            services[i].sub_products = [];
        }
        setData('services', services);
    };

    const handleSelectProduct = (product: any) => {
        if (pickerTarget === null) return;
        const { svcIdx, subIdx } = pickerTarget;

        if (subIdx !== undefined) {
            const services = [...data.services];
            services[svcIdx].sub_products[subIdx] = {
                ...services[svcIdx].sub_products[subIdx],
                product_id: product.id,
            };
            setData('services', services);
        } else {
            const services = [...data.services];
            services[svcIdx] = {
                ...services[svcIdx],
                product_id:   product.id,
                unit_price:   services[svcIdx].unit_price || product.price,
                total_price:  (services[svcIdx].quantity || 1) * (services[svcIdx].unit_price || product.price),
                sub_products: [],
            };
            setData('services', services);
        }
    };

    const addService    = () => setData('services', [...data.services, { product_id: '', quantity: 1, unit_price: '', total_price: 0, location: '', sub_products: [] }]);
    const removeService = (i: number) => setData('services', data.services.filter((_: any, idx: number) => idx !== i));

    const addSubProduct = (svcIdx: number) => {
        const services = [...data.services];
        services[svcIdx].sub_products = [...(services[svcIdx].sub_products ?? []), { product_id: '', quantity: 1 }];
        setData('services', services);
    };
    const updateSubProduct = (svcIdx: number, subIdx: number, field: string, value: any) => {
        const services = [...data.services];
        services[svcIdx].sub_products[subIdx] = { ...services[svcIdx].sub_products[subIdx], [field]: value };
        setData('services', services);
    };
    const removeSubProduct = (svcIdx: number, subIdx: number) => {
        const services = [...data.services];
        services[svcIdx].sub_products = services[svcIdx].sub_products.filter((_: any, idx: number) => idx !== subIdx);
        setData('services', services);
    };

    const totalServices = data.services.reduce((s: number, it: any) => s + (it.total_price || 0), 0);

    // Incentive calculations
    const contractVal = parseFloat(data.contract_value) || 0;
    const canvasIncentive = data.sales_type === 'canvas' ? contractVal * 0.04 : 0;
    const leadSalesIncentive = data.sales_type === 'lead' ? contractVal * 0.02 : 0;
    const leadGiverIncentive = data.sales_type === 'lead' ? contractVal * 0.02 : 0;

    const submit = (e: React.FormEvent) => {
        e.preventDefault();
        const filledIds = data.services.filter((s: any) => s.product_id).map((s: any) => s.product_id);
        if (filledIds.length !== new Set(filledIds).size) {
            setDuplicateError('Produk tidak boleh duplikat dalam layanan kontrak.');
            return;
        }
        setDuplicateError('');
        editing ? put(`/contracts/${contract.id}`) : post('/contracts');
    };

    return (
        <AppLayout header={editing ? 'Edit Kontrak' : 'Tambah Kontrak'}>
            <Head title={editing ? 'Edit Kontrak' : 'Tambah Kontrak'} />

            {customerPickerOpen && (
                <CustomerPickerModal
                    customers={customers ?? []}
                    onSelect={c => setData('customer_id', c.id)}
                    onClose={() => setCustomerPickerOpen(false)}
                />
            )}

            {pickerTarget !== null && (
                <ProductPickerModal
                    products={products ?? []}
                    onSelect={handleSelectProduct}
                    onClose={() => setPickerTarget(null)}
                    extraLabel="Harga"
                    extraKey="price"
                    extraFormat="currency"
                />
            )}

            <div className="max-w-5xl bg-white rounded-xl shadow p-6">
                <form onSubmit={submit} className="space-y-4">

                    {/* Header */}
                    <div className="grid grid-cols-2 gap-4">
                        <FormField label="No. Kontrak" error={errors.contract_number} required>
                            <input className={inputCls} value={data.contract_number} onChange={e => setData('contract_number', e.target.value)} />
                        </FormField>
                        <FormField label="Status">
                            <select className={inputCls} value={data.status} onChange={e => setData('status', e.target.value)}>
                                <option value="draft">Draft</option>
                                <option value="active">Aktif</option>
                                <option value="completed">Selesai</option>
                                <option value="cancelled">Dibatalkan</option>
                            </select>
                        </FormField>
                    </div>

                    <FormField label="Customer" error={errors.customer_id} required>
                        <button
                            type="button"
                            onClick={() => setCustomerPickerOpen(true)}
                            className="w-full text-left px-3 py-2 border rounded-md text-sm bg-white hover:border-emerald-400 focus:outline-none focus:ring-2 focus:ring-emerald-400 transition"
                        >
                            {selectedCustomer
                                ? <span className="text-gray-800">{selectedCustomer.name}</span>
                                : <span className="text-gray-400">— Pilih Customer —</span>
                            }
                        </button>
                    </FormField>

                    <div className="grid grid-cols-2 gap-4">
                        <FormField label="Tanggal Mulai" error={errors.start_date} required>
                            <input type="date" className={inputCls} value={data.start_date} onChange={e => setData('start_date', e.target.value)} />
                        </FormField>
                        <FormField label="Tanggal Selesai" error={errors.end_date} required>
                            <input type="date" className={inputCls} value={data.end_date} onChange={e => setData('end_date', e.target.value)} />
                        </FormField>
                    </div>

                    <FormField label="Nilai Kontrak (Rp)" error={errors.contract_value} required>
                        <input type="number" className={inputCls} value={data.contract_value} onChange={e => setData('contract_value', e.target.value)} />
                    </FormField>

                    <FormField label="Area Layanan" error={errors.service_area} required>
                        <input className={inputCls} value={data.service_area} onChange={e => setData('service_area', e.target.value)} />
                    </FormField>

                    {/* Frequencies */}
                    <div className="grid grid-cols-2 gap-4">
                        <FormField label="Frekuensi Kunjungan (total)" error={errors.visit_frequency} required>
                            <input
                                type="number" min={1}
                                className={inputCls}
                                value={data.visit_frequency}
                                onChange={e => setData('visit_frequency', +e.target.value)}
                            />
                            <p className="text-xs text-gray-400 mt-1">Total kunjungan selama periode kontrak</p>
                        </FormField>
                        <FormField label="Frekuensi Invoice Termin" error={errors.invoice_frequency} required>
                            <input
                                type="number" min={1}
                                className={inputCls}
                                value={data.invoice_frequency}
                                onChange={e => setData('invoice_frequency', +e.target.value)}
                            />
                            <p className="text-xs text-gray-400 mt-1">Jumlah termin penagihan invoice</p>
                        </FormField>
                    </div>

                    {/* Sales Input */}
                    <div className="border rounded-lg p-4 bg-gray-50 space-y-3">
                        <h3 className="font-semibold text-gray-700 text-sm">Informasi Sales</h3>
                        <FormField label="Tipe Sales">
                            <div className="flex gap-6">
                                {[{ val: '', label: 'Tidak Ada' }, { val: 'canvas', label: 'Canvas' }, { val: 'lead', label: 'Lead' }].map(opt => (
                                    <label key={opt.val} className="flex items-center gap-2 cursor-pointer">
                                        <input
                                            type="radio"
                                            name="sales_type"
                                            value={opt.val}
                                            checked={data.sales_type === opt.val}
                                            onChange={() => setData({ ...data, sales_type: opt.val, sales_employee_id: '', lead_employee_id: '' })}
                                            className="w-4 h-4 text-emerald-600 focus:ring-emerald-500"
                                        />
                                        <span className="text-sm text-gray-700">{opt.label}</span>
                                    </label>
                                ))}
                            </div>
                        </FormField>

                        {data.sales_type === 'canvas' && (
                            <div className="space-y-3">
                                <FormField label="Sales (Canvas)" error={errors.sales_employee_id} required>
                                    <select
                                        className={inputCls}
                                        value={data.sales_employee_id}
                                        onChange={e => setData('sales_employee_id', e.target.value)}
                                    >
                                        <option value="">— Pilih Karyawan —</option>
                                        {employees?.map((emp: any) => (
                                            <option key={emp.id} value={emp.id}>
                                                {emp.name}{emp.position ? ` — ${emp.position}` : ''}
                                            </option>
                                        ))}
                                    </select>
                                </FormField>
                                <div className="rounded-md bg-emerald-50 border border-emerald-200 px-3 py-2 text-sm text-emerald-800">
                                    Insentif Sales Canvas: <strong>{fmt(canvasIncentive)}</strong> (4% dari nilai kontrak)
                                </div>
                            </div>
                        )}

                        {data.sales_type === 'lead' && (
                            <div className="space-y-3">
                                <div className="grid grid-cols-2 gap-4">
                                    <FormField label="Sales" error={errors.sales_employee_id} required>
                                        <select
                                            className={inputCls}
                                            value={data.sales_employee_id}
                                            onChange={e => setData('sales_employee_id', e.target.value)}
                                        >
                                            <option value="">— Pilih Karyawan —</option>
                                            {employees?.map((emp: any) => (
                                                <option key={emp.id} value={emp.id}>
                                                    {emp.name}{emp.position ? ` — ${emp.position}` : ''}
                                                </option>
                                            ))}
                                        </select>
                                    </FormField>
                                    <FormField label="Pemberi Lead" error={errors.lead_employee_id} required>
                                        <select
                                            className={inputCls}
                                            value={data.lead_employee_id}
                                            onChange={e => setData('lead_employee_id', e.target.value)}
                                        >
                                            <option value="">— Pilih Karyawan —</option>
                                            {employees?.map((emp: any) => (
                                                <option key={emp.id} value={emp.id}>
                                                    {emp.name}{emp.position ? ` — ${emp.position}` : ''}
                                                </option>
                                            ))}
                                        </select>
                                    </FormField>
                                </div>
                                <div className="rounded-md bg-emerald-50 border border-emerald-200 px-3 py-2 text-sm text-emerald-800 space-y-1">
                                    <div>Insentif Sales: <strong>{fmt(leadSalesIncentive)}</strong> (2% dari nilai kontrak)</div>
                                    <div>Insentif Pemberi Lead: <strong>{fmt(leadGiverIncentive)}</strong> (2% dari nilai kontrak)</div>
                                </div>
                            </div>
                        )}
                    </div>

                    {/* Product / service items */}
                    <div>
                        <h3 className="font-semibold text-gray-700 mb-2">Item Produk / Layanan</h3>
                        {(duplicateError || errors.services) && (
                            <div className="mb-2 rounded-md bg-red-50 border border-red-200 px-3 py-2 text-sm text-red-600">
                                {duplicateError || errors.services}
                            </div>
                        )}
                        <div className="border rounded-lg overflow-hidden mb-2">
                            <table className="w-full text-sm">
                                <thead className="bg-gray-50 border-b">
                                    <tr className="text-left text-gray-600">
                                        <th className="px-3 py-2">Produk</th>
                                        <th className="px-3 py-2 w-16">Sat.</th>
                                        <th className="px-3 py-2 w-20">Qty</th>
                                        <th className="px-3 py-2 w-36">Harga Satuan</th>
                                        <th className="px-3 py-2 w-36">Lokasi</th>
                                        <th className="px-3 py-2 w-32 text-right">Total</th>
                                        <th className="px-3 py-2 w-8"></th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y">
                                    {data.services.length === 0 && (
                                        <tr>
                                            <td colSpan={7} className="px-3 py-4 text-center text-gray-400">
                                                Belum ada item. Klik "+ Tambah Item" untuk menambahkan.
                                            </td>
                                        </tr>
                                    )}
                                    {data.services.map((svc: any, i: number) => {
                                        const selectedProduct = getProduct(svc.product_id);
                                        const isService = selectedProduct?.product_type === 'service';
                                        return (
                                            <>
                                                <tr key={`svc-${i}`} className="align-top">
                                                    <td className="px-3 py-2">
                                                        <button
                                                            type="button"
                                                            onClick={() => setPickerTarget({ svcIdx: i })}
                                                            className="w-full text-left px-3 py-1.5 border rounded-md text-sm bg-white hover:border-emerald-400 focus:outline-none focus:ring-2 focus:ring-emerald-400 transition"
                                                        >
                                                            {selectedProduct
                                                                ? <span className="text-gray-800">{selectedProduct.name}</span>
                                                                : <span className="text-gray-400">— Pilih Produk —</span>
                                                            }
                                                        </button>
                                                    </td>
                                                    <td className="px-3 py-2 text-gray-500 text-xs">{selectedProduct?.unit ?? '—'}</td>
                                                    <td className="px-3 py-2">
                                                        <input type="number" min={1} className={inputCls} value={svc.quantity} onChange={e => updateService(i, 'quantity', +e.target.value)} />
                                                    </td>
                                                    <td className="px-3 py-2">
                                                        <input type="number" className={inputCls} value={svc.unit_price} onChange={e => updateService(i, 'unit_price', +e.target.value)} placeholder={selectedProduct?.price ?? ''} />
                                                    </td>
                                                    <td className="px-3 py-2">
                                                        <input className={inputCls} value={svc.location} onChange={e => updateService(i, 'location', e.target.value)} placeholder="cth: Lantai 1" />
                                                    </td>
                                                    <td className="px-3 py-2 text-right font-medium whitespace-nowrap">{fmt(svc.total_price || 0)}</td>
                                                    <td className="px-3 py-2">
                                                        <button type="button" onClick={() => removeService(i)} className="text-red-500 text-lg leading-none hover:text-red-700">×</button>
                                                    </td>
                                                </tr>

                                                {isService && (
                                                    <tr key={`sub-${i}`} className="bg-blue-50">
                                                        <td colSpan={7} className="px-4 py-2">
                                                            <div className="flex items-center justify-between mb-1">
                                                                <span className="text-xs font-semibold text-blue-700">Sub Produk Layanan</span>
                                                                <button type="button" onClick={() => addSubProduct(i)} className="text-xs text-blue-600 hover:underline">+ Tambah Sub Produk</button>
                                                            </div>
                                                            {(svc.sub_products ?? []).length === 0 && (
                                                                <p className="text-xs text-blue-400 italic">Belum ada sub produk.</p>
                                                            )}
                                                            {(svc.sub_products ?? []).length > 0 && (
                                                                <table className="w-full text-xs mt-1">
                                                                    <thead>
                                                                        <tr className="text-left text-blue-600 border-b border-blue-100">
                                                                            <th className="pb-1 pr-2">Produk</th>
                                                                            <th className="pb-1 w-24">Qty</th>
                                                                            <th className="pb-1 w-8"></th>
                                                                        </tr>
                                                                    </thead>
                                                                    <tbody className="divide-y divide-blue-100">
                                                                        {svc.sub_products.map((sub: any, si: number) => {
                                                                            const subProduct = getProduct(sub.product_id);
                                                                            return (
                                                                                <tr key={si}>
                                                                                    <td className="py-1 pr-2">
                                                                                        <button
                                                                                            type="button"
                                                                                            onClick={() => setPickerTarget({ svcIdx: i, subIdx: si })}
                                                                                            className="w-full text-left px-2 py-1 border rounded text-xs bg-white hover:border-blue-400 focus:outline-none focus:ring-1 focus:ring-blue-400 transition"
                                                                                        >
                                                                                            {subProduct ? <span className="text-gray-800">{subProduct.name}</span> : <span className="text-gray-400">— Pilih Produk —</span>}
                                                                                        </button>
                                                                                    </td>
                                                                                    <td className="py-1 pr-2">
                                                                                        <input type="number" min={1} className={inputCls} value={sub.quantity} onChange={e => updateSubProduct(i, si, 'quantity', +e.target.value)} />
                                                                                    </td>
                                                                                    <td className="py-1">
                                                                                        <button type="button" onClick={() => removeSubProduct(i, si)} className="text-red-400 hover:text-red-600 text-base leading-none">×</button>
                                                                                    </td>
                                                                                </tr>
                                                                            );
                                                                        })}
                                                                    </tbody>
                                                                </table>
                                                            )}
                                                        </td>
                                                    </tr>
                                                )}
                                            </>
                                        );
                                    })}
                                </tbody>
                                {data.services.length > 0 && (
                                    <tfoot className="bg-gray-50 border-t">
                                        <tr>
                                            <td colSpan={5} className="px-3 py-2 text-right font-semibold text-gray-700">Total Item</td>
                                            <td className="px-3 py-2 text-right font-bold text-emerald-700">{fmt(totalServices)}</td>
                                            <td></td>
                                        </tr>
                                    </tfoot>
                                )}
                            </table>
                        </div>
                        <button type="button" onClick={addService} className="text-sm text-emerald-600 hover:underline">+ Tambah Item</button>
                    </div>

                    {/* Visit Plans Table */}
                    <div>
                        <div className="flex items-center justify-between mb-2">
                            <h3 className="font-semibold text-gray-700">Rencana Kunjungan</h3>
                            <button
                                type="button"
                                onClick={regeneratePlans}
                                className="text-xs text-blue-600 hover:underline border border-blue-300 rounded px-2 py-1"
                            >
                                ↺ Generate ulang dari frekuensi
                            </button>
                        </div>
                        <div className="border rounded-lg overflow-hidden">
                            <table className="w-full text-sm">
                                <thead className="bg-gray-50 border-b">
                                    <tr className="text-left text-gray-600">
                                        <th className="px-3 py-2 w-16">No.</th>
                                        <th className="px-3 py-2 w-40">Tanggal Rencana</th>
                                        <th className="px-3 py-2">Keterangan</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y">
                                    {data.visit_plans.length === 0 && (
                                        <tr>
                                            <td colSpan={3} className="px-3 py-4 text-center text-gray-400">
                                                Isi Tanggal Mulai, Tanggal Selesai, dan Frekuensi Kunjungan untuk generate rencana kunjungan.
                                            </td>
                                        </tr>
                                    )}
                                    {data.visit_plans.map((vp: any, i: number) => (
                                        <tr key={i} className="align-middle">
                                            <td className="px-3 py-2 text-gray-500 font-medium">{vp.visit_number}</td>
                                            <td className="px-3 py-2">
                                                <input
                                                    type="date"
                                                    className={inputCls}
                                                    value={vp.planned_date}
                                                    onChange={e => updateVisitPlan(i, 'planned_date', e.target.value)}
                                                />
                                            </td>
                                            <td className="px-3 py-2">
                                                <input
                                                    className={inputCls}
                                                    value={vp.notes}
                                                    onChange={e => updateVisitPlan(i, 'notes', e.target.value)}
                                                    placeholder="Keterangan (opsional)"
                                                />
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                        {data.visit_plans.length > 0 && (
                            <p className="text-xs text-gray-400 mt-1">
                                {data.visit_plans.length} rencana kunjungan. Tanggal dapat disesuaikan secara manual.
                            </p>
                        )}
                    </div>

                    <FormField label="Catatan">
                        <textarea rows={3} className={inputCls} value={data.notes} onChange={e => setData('notes', e.target.value)} />
                    </FormField>

                    <div className="flex gap-3 pt-2">
                        <button type="submit" disabled={processing} className="px-5 py-2 rounded-md bg-emerald-600 text-white text-sm font-medium hover:bg-emerald-700 disabled:opacity-60">
                            {processing ? 'Menyimpan...' : 'Simpan'}
                        </button>
                        <Link href="/contracts" className="px-5 py-2 rounded-md border border-gray-300 text-sm text-gray-700 hover:bg-gray-50">Batal</Link>
                    </div>
                </form>
            </div>
        </AppLayout>
    );
}
